version: '3.8'
name: dbtest-compose
networks:
  dbnetwork:
    external: true

services:

  dbtest:
    container_name: DBTEst
    image: dbtest
    ports:
      - "1551:1433"
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: true
    volumes:
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https
    networks:
      - dbnetwork
    
  dbtest.replica:
    container_name: DBTEst.Replica
    image: dbtest
    ports:
      - "1552:1433"
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: true
    volumes:
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https
    networks:
      - dbnetwork
